quarkus.application.name=eip-observability

kafka.brokers=localhost:9092

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/eipdb
quarkus.datasource.username=eipuser
quarkus.datasource.password=eippass

camel.main.message-history=true

quarkus.http.port=8082

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG

# Use the Podman stack Kafka, not Quarkus Dev Services
quarkus.kafka.devservices.enabled=false
