quarkus.application.name=eip-observability

kafka.brokers=localhost:9092

camel.main.message-history=true

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG
