quarkus.application.name=eip-testing-strategies

kafka.brokers=localhost:9092

quarkus.http.port=8082

payment.gateway.mode=mock

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG

quarkus.kafka.devservices.enabled=false
