quarkus.application.name=eip-observability-stack

kafka.brokers=localhost:9092

quarkus.http.port=8087

# OpenTelemetry
quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
quarkus.otel.exporter.otlp.protocol=grpc
camel.opentelemetry.enabled=true
camel.opentelemetry.exclude-patterns=timer:*

# Logging
quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG

quarkus.kafka.devservices.enabled=false
