quarkus.application.name=eip-kafka-consumer-tuning

kafka.brokers=localhost:9092

quarkus.http.port=8088

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG

quarkus.kafka.devservices.enabled=false
