quarkus.application.name=eip-channel-types

kafka.brokers=localhost:9092
camel.component.pulsar.service-url=pulsar://localhost:6650

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG
