quarkus.application.name=eip-channel-infra

kafka.brokers=localhost:9092
camel.component.pulsar.service-url=pulsar://localhost:6650

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/eipdb
quarkus.datasource.username=eipuser
quarkus.datasource.password=eippass

quarkus.http.port=8082

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG
