quarkus.application.name=eip-endpoints

kafka.brokers=localhost:9092
camel.component.pulsar.service-url=pulsar://localhost:6650

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/eipdb
quarkus.datasource.username=eipuser
quarkus.datasource.password=eippass

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG

# Avoid port 8080 conflict with Pulsar admin
quarkus.http.port=8082

# Use the Podman stack Kafka, not Quarkus Dev Services
quarkus.kafka.devservices.enabled=false
