spring.application.name=eip-k8s-deploy

kafka.brokers=localhost:9092

spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8088

camel.servlet.mapping.context-path=/api/*

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

logging.level.org.apache.camel=INFO
logging.level.com.example.eip=DEBUG
