# Kafka
camel.component.kafka.brokers=localhost:9092
camel.component.kafka.group-id=eip-cli-demo

# Redis
camel.component.redis-lettuce.host=localhost
camel.component.redis-lettuce.port=6379

# REST
camel.rest.port=8088
camel.rest.binding-mode=json
