quarkus.application.name=eip-drools-rules

kafka.brokers=localhost:9092

quarkus.http.port=8086

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG
quarkus.log.category."org.drools".level=INFO

quarkus.kafka.devservices.enabled=false
