quarkus.application.name=eip-redis-integration

kafka.brokers=localhost:9092

quarkus.redis.hosts=redis://localhost:6379
quarkus.redis.max-pool-size=20

quarkus.http.port=8085

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG

quarkus.kafka.devservices.enabled=false
