#!/usr/bin/env python3
"""Parse SVGs generated by generate_diagram.py and output equivalent emit() calls.

Each SVG has a predictable structure:
- <rect rx="12" ...> = band
- <rect rx="9" ...> = node
- <path d="M... L..." ...> = edge
- Free <text> elements (not inside a node) = note
"""
import re, sys, os, glob
from xml.dom.minidom import parseString

STYLES_BY_COLORS = {
    ("#ffffff", "#111111"): "box",
    ("#ffffff", "#999999"): "sub",
    ("#fff8ef", "#e8870c"): "accent",
    ("#f4f4f4", "#888888"): "muted",
    ("#f4f4f4", "#666666"): "muted",
    ("#eef4fb", "#2f6db5"): "info",
    ("#111111", "#111111"): "ink",
}

def parse_svg(filepath):
    content = open(filepath).read()
    dom = parseString(content)
    svg = dom.documentElement
    vb = svg.getAttribute("viewBox").split()
    width, height = int(vb[2]), int(vb[3])

    bands = []
    nodes = []
    edges = []
    notes = []

    # Track which text elements belong to nodes (by position)
    node_rects = []  # (x, y, w, h, fill, stroke)

    for el in svg.getElementsByTagName("rect"):
        x = float(el.getAttribute("x"))
        y = float(el.getAttribute("y"))
        w = float(el.getAttribute("width"))
        h = float(el.getAttribute("height"))
        rx = el.getAttribute("rx")
        fill = el.getAttribute("fill").lower()
        stroke = el.getAttribute("stroke").lower()

        if rx == "12":
            bands.append({"x": int(x), "y": int(y), "w": int(w), "h": int(h), "fill": fill})
        elif rx == "9":
            node_rects.append((x, y, w, h, fill, stroke))

    # Collect all text elements
    all_texts = []
    for el in svg.getElementsByTagName("text"):
        tx = float(el.getAttribute("x"))
        ty = float(el.getAttribute("y"))
        text_content = el.firstChild.nodeValue if el.firstChild else ""
        font_size = el.getAttribute("font-size")
        fill = el.getAttribute("fill").lower() if el.getAttribute("fill") else "#111111"
        anchor = el.getAttribute("text-anchor") or "start"
        bold = el.getAttribute("font-weight") == "700"
        all_texts.append({
            "x": tx, "y": ty, "text": text_content,
            "size": font_size, "fill": fill, "anchor": anchor, "bold": bold
        })

    # Match texts to bands (band labels are at x+12, y+20, font-size 12, fill #888 or #555)
    band_texts = set()
    for i, b in enumerate(bands):
        for j, t in enumerate(all_texts):
            if (abs(t["x"] - (b["x"] + 12)) < 2 and
                abs(t["y"] - (b["y"] + 20)) < 2 and
                t["size"] == "12"):
                bands[i]["label"] = t["text"]
                band_texts.add(j)

    # Match texts to nodes (centered text inside node rect bounds)
    node_texts = {}  # node_idx -> [texts]
    text_claimed = set(band_texts)

    for ni, (nx, ny, nw, nh, nfill, nstroke) in enumerate(node_rects):
        cx = nx + nw/2
        node_texts[ni] = []
        for ti, t in enumerate(all_texts):
            if ti in text_claimed:
                continue
            # Check if text is centered on this node (within bounds)
            if (t["anchor"] == "middle" and
                abs(t["x"] - cx) < 2 and
                ny - 2 <= t["y"] <= ny + nh + 5):
                node_texts[ni].append((t["y"], t["text"]))
                text_claimed.add(ti)

    # Build node objects
    for ni, (nx, ny, nw, nh, nfill, nstroke) in enumerate(node_rects):
        style_key = (nfill, nstroke)
        style = STYLES_BY_COLORS.get(style_key, "box")
        lines = [t[1] for t in sorted(node_texts.get(ni, []), key=lambda x: x[0])]
        node = {"x": int(nx), "y": int(ny), "w": int(nw), "h": int(nh)}
        if style != "box":
            node["style"] = style
        if lines:
            node["lines"] = lines
        nodes.append(node)

    # Parse edges (skip paths inside <defs> — marker arrowheads)
    defs_paths = set()
    for defs in svg.getElementsByTagName("defs"):
        for p in defs.getElementsByTagName("path"):
            defs_paths.add(p)

    for el in svg.getElementsByTagName("path"):
        if el in defs_paths:
            continue
        d = el.getAttribute("d")
        m = re.match(r'M([\d.]+),([\d.]+)\s+L([\d.]+),([\d.]+)', d)
        if not m:
            continue
        x1, y1, x2, y2 = [float(v) for v in m.groups()]
        stroke = el.getAttribute("stroke").lower()
        marker_end = el.getAttribute("marker-end")
        marker_start = el.getAttribute("marker-start")
        dash = el.getAttribute("stroke-dasharray")

        edge = {"x1": int(x1), "y1": int(y1), "x2": int(x2), "y2": int(y2)}
        if "#b8650a" in stroke:
            edge["amber"] = True
        if dash:
            edge["dashed"] = True
        if marker_start:
            edge["bidir"] = True
        edges.append(edge)

    # Remaining texts are notes (also skip white halo texts)
    for ti, t in enumerate(all_texts):
        if ti in text_claimed:
            continue
        if t["fill"] in ("#ffffff", "white"):
            continue
        # Skip edge labels (handled separately)
        is_edge_label = False
        for e in edges:
            mx = (e["x1"] + e["x2"]) / 2
            my = (e["y1"] + e["y2"]) / 2
            if abs(t["x"] - mx) < 20 and abs(t["y"] - my) < 20:
                # This is an edge label
                e["label"] = t["text"]
                lx = t["x"] - mx
                ly = t["y"] - my
                if abs(lx - 6) > 2:
                    e["lx"] = int(lx)
                if abs(ly - (-6)) > 2:
                    e["ly"] = int(ly)
                is_edge_label = True
                text_claimed.add(ti)
                break
        if is_edge_label:
            continue

        note = {"x": int(t["x"]), "y": int(t["y"]), "text": t["text"]}
        if t["anchor"] != "start":
            note["anchor"] = t["anchor"]
        if t["bold"]:
            note["bold"] = True
        if t["size"] and t["size"] != "11":
            note["size"] = int(float(t["size"]))
        notes.append(note)
        text_claimed.add(ti)

    # Clean up band fill defaults
    for b in bands:
        if b["fill"] == "#fafafa":
            del b["fill"]

    return width, height, bands, nodes, edges, notes


def emit_code(name, width, height, bands, nodes, edges, notes):
    """Generate Python code for a g.emit() call."""
    lines = []
    lines.append(f'# --- {name} ---')
    lines.append(f'g.emit("{name}", {width}, {height},')

    if bands:
        lines.append('    bands=[')
        for b in bands:
            lines.append(f'        {b},')
        lines.append('    ],')

    if nodes:
        lines.append('    nodes=[')
        for n in nodes:
            lines.append(f'        {n},')
        lines.append('    ],')

    if edges:
        lines.append('    edges=[')
        for e in edges:
            lines.append(f'        {e},')
        lines.append('    ],')

    if notes:
        lines.append('    notes=[')
        for n in notes:
            lines.append(f'        {n},')
        lines.append('    ],')

    lines.append(')')
    lines.append('')
    return '\n'.join(lines)


if __name__ == "__main__":
    diagrams_dir = "assets/diagrams"

    # Chapter diagrams not handled by other scripts
    appendix_handled = {"22-appendix-redis", "24-appendix-drools", "25-appendix-quarkus-flow", "27-appendix-observability"}

    output_lines = [
        '#!/usr/bin/env python3',
        '"""Regenerate all chapter diagrams (those not handled by generate_example_diagrams.py',
        'or generate_appendix_diagrams.py)."""',
        'import sys; sys.path.insert(0, "scripts")',
        'import generate_diagram as g',
        'g.OUT = "assets/diagrams"',
        '',
    ]

    count = 0
    for svg_path in sorted(glob.glob(f"{diagrams_dir}/[0-9]*.svg")):
        name = os.path.basename(svg_path).replace(".svg", "")
        if name in appendix_handled:
            continue
        if name.startswith("ex-"):
            continue

        try:
            w, h, bands, nodes, edges, notes = parse_svg(svg_path)
            output_lines.append(emit_code(name, w, h, bands, nodes, edges, notes))
            count += 1
        except Exception as e:
            output_lines.append(f'# ERROR parsing {name}: {e}')
            output_lines.append('')

    output_lines.append(f'print(f"Done — {count} chapter diagram pairs generated in {{g.OUT}}")')

    script_path = "scripts/generate_chapter_diagrams.py"
    with open(script_path, "w") as f:
        f.write('\n'.join(output_lines) + '\n')

    print(f"Generated {script_path} with {count} diagrams")
