quarkus.application.name=eip-kafka-deep-dive

kafka.brokers=localhost:9092

quarkus.http.port=8083

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG

quarkus.kafka.devservices.enabled=false
