quarkus.application.name=eip-pulsar-deep-dive

pulsar.service.url=pulsar://localhost:6650
camel.component.pulsar.service-url=pulsar://localhost:6650

quarkus.http.port=8084

quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG

quarkus.kafka.devservices.enabled=false
