quarkus.application.name=eip-loan-broker

# Kafka broker
kafka.brokers=localhost:9092

# Logging
quarkus.log.category."org.apache.camel".level=INFO
quarkus.log.category."com.example.eip".level=DEBUG

# Avoid port 8080 conflict with Pulsar admin
quarkus.http.port=8082

# Use the Podman stack Kafka, not Quarkus Dev Services
quarkus.kafka.devservices.enabled=false
